### ISSUE TITLE
Ability to deploy slide-atlas automatically using vagrant and salt    

### ISSUE THREAD

**Issue by dhandeo** [SlideAtlas/SlideAtlas-Server#20]
Multiple subtasks  in this issue -
- Use vagrant to setup a development virtual machine 
- Use salt / or shell scripts to deploy 
- Add code to bootstrap slide-atlas (add first user etc)  
- Automated creation of development database 
- Enhance the deployment for production server

**Comment by brianhelba** [comment]
Will fix with Girder.
