### ISSUE TITLE
Json response from  /sessions  

### ISSUE THREAD

**Issue by dhandeo** [SlideAtlas/SlideAtlas-Server#68]
Currently json response from  /sessions omits rule information, that should be included to be able to display them correctly. 

``` json
ajax: 1,
name: "Admin @ Harvard Combined Dermatology Residency Training Program",
sessions: [
rule: "",
sessions: [ ... ]
]
```

Additionally will like to see more information form the same query  ? 
- i.e. # of views in them
- Dereferenced list of views (with views=1), this will avoid more queries to come

**Comment by brianhelba** [comment]
Will fix with Girder.
