### ISSUE TITLE
Improve performance of views filtering 

### ISSUE THREAD

**Issue by dhandeo** [SlideAtlas/SlideAtlas-Server#77]
1) Load the thumbnails in the list, that way when the list shows up it is ready
2) Debounce the input, so filtering will wait until the input stabilizes for say 0.3 seconds (http://stackoverflow.com/questions/21088845/can-i-debounce-or-throttle-a-watched-input-in-angularjs-using-lodash)
3) Paginate

**Comment by brianhelba** [comment]
Will fix with Girder.
