### ISSUE TITLE
Support image importing from an ftp service

### ISSUE THREAD

**Issue by dhandeo** [SlideAtlas/SlideAtlas-Server#82]
Streamline uploading for collaborators that can upload files using ftp service.

The add configuration to the image_store image store will be configured with an FTP service, and will poll for any new files there, and the new files will be imported similar to microscope workflow, and will be put in the Inbox of that user.

The question is whether to have individual image_stores for each collaboration ? or add the configuration separately, and import all the images to a same image_store

**Comment by brianhelba** [comment]
Will fix with Girder.
