### ISSUE TITLE
Search feature needs enhancement

### ISSUE THREAD

**Issue by dhandeo** [SlideAtlas/SlideAtlas-Server#85]
"Search has to work in a way that gives useful results to pathologists. As it is, voice search for 'alopecia stack' returns "alopecia stack" (in double quotes) for which there are no hits. If they just type the words in not using quotes, they get a list of all sessions that have either word then all views that have either word. When they use multiple terms, they are attempting to refine the search. What they will want to see is a prioritized list of results (like you get with Google search). The list should have the following order:  1) hits that match the entered terms exactly as entered (ie, in quotes) , 2) hits that have both terms (ANDed) and finally 3) hits that match for either term (ORed). If the hit is a collection or session, this item should be displayed as a closed accordian. If it is a view, they will want the list item for that view to show the corresponding collection and session too. Another issue is that voice search sometimes does not respond quickly. There can be a delay of 5-10 seconds before any text appears in the search field. The user has no indication that their voice commands have been heard. They need some immediate feedback that the voice search is actually working.

Finally I think the search results have to be saved. If they do a search, open a view and then decide that this not what they are looking for, they will want to go back and try opening another. If they go back and find the search results are lost or their place in the list is not preserved, it will make search very frustrating to use.

Please get rid of the text describing how to enter the search query."

**Comment by brianhelba** [comment]
Will fix with Girder.
